Order birthdays by date
Boufcoulman/wholesome-translator pull request #31
Opened 2021-08-09 21:43 UTC by christophe-riolo

Some cleanup and ordering of birthdays

2021-08-09 21:43 UTC, christophe-riolo commented on lib/birthday_lib.py
> +    users = [user_record[0] for user_record in cursor]
le curseur est iterable directement

2021-08-09 21:44 UTC, christophe-riolo commented on lib/birthday_lib.py
> +    birthdays = [Birthday(*record) for record in cursor]
Unpack le résultat et c'est plus propre :)

2021-08-09 21:45 UTC, christophe-riolo commented on lib/birthday_lib.py
> +MOIS_INV = dict(zip(MOIS.values(), MOIS.keys()))
Créer ces deux dictionnaires rendent la manipulation plus siple qu'une liste après

2022-08-31 07:20 UTC, Boufcoulman requested changes

2022-08-31 07:22 UTC, christophe-riolo commented on lib/birthday_lib.py
> +    ORDER BY SUBSTR(birthday, 4, 2), SUBSTR(birthday, 1,2)
Mais on ne devrait plus avoir ça, j'ai fait la migration de la base, et normalement avec la conversion en ISO il y a toujours deux chiffres (ex 04)
Il faudrait voir si les tests couvrent bien ça

2022-08-31 07:23 UTC, christophe-riolo commented on lib/birthday_lib.py
> +    except OverflowError:
Ça me va, la documentation de `parse` n'annonçait que cette exception là, elle est incomplète on dirait :roll_eyes:

2022-08-31 07:26 UTC, christophe-riolo commented on lib/birthday_lib.py
> +    # 1964 is a leap year, so it will allow the 29 of february
À quel moment on passe un tuple ? Parce que j'ai déclaré que l'argument est un str, est-ce qu'il faudrait mettre cette ligne ailleurs, dans les commandes ?

2022-09-01 11:41 UTC, Boufcoulman commented on lib/birthday_lib.py
> +    ORDER BY SUBSTR(birthday, 4, 2), SUBSTR(birthday, 1,2)
oui oui c'est tout bon

2022-09-01 11:43 UTC, Boufcoulman commented on lib/birthday_lib.py
> +    # 1964 is a leap year, so it will allow the 29 of february
dans l'input de la commande, le premier argument après %bd.add c'est le nom de l'utilisateur, et tout ce qui suit est mis dans le tuple date_input
`async def update(self, ctx, user_info, *date_input) -> None:`

2022-09-01 11:54 UTC, christophe-riolo commented on lib/birthday_lib.py
> +    # 1964 is a leap year, so it will allow the 29 of february
Je vais du coup modifier la commande, mais je me demande pourquoi mypy n'a pas détecté ça ... ou alors il ne tourne juste pas :thinking:

2022-09-01 19:14 UTC, merged